---
name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build Docker image and push to Dockerhub"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 # This is the region to authenticate against for public ECR repositories
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::118330671040:role/node-indexer-ci
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Install prerequisites for Docker build
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build and push Docker images
        env:
          DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        run: |
          make image-push
