---
name: "Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Build Docker image and push to Dockerhub"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Lint
      run: make lint

    - name: Test
      run: make test
